### ISSUE TITLE
Suggestion: Upload as .crx?

### ISSUE THREAD

**Issue by yannym** [xwartz/earthview#1]
Would it be possible to upload this as a CRX file, that way those who are less "tech" inclined could easily install this. I don't think Chrome stable is on v50 yet, but some people on the Dev build might find it easier to just download the CRX.

**Comment by xwartz** [comment]
OK, I upload one. (https://github.com/xwartz/earthview/releases/tag/2.11.1)

But i heard Chrome can only install Chrome extensions from the Chrome Web Store (http://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html).

And [how to How to install a Chrome extension from GitHub](https://www.mattcutts.com/blog/how-to-install-a-chrome-extension-from-github/)

**Comment by yannym** [comment]
I just tried it on my Chromebook running Chrome Dev 50.0.2661.32, installing a .crx file only works for me if I drag the .crx file into the extensions page. The upside of having a crx file, is that you can install the crx and delete it after that, by loading the unpacked extension you have to keep that folder there, and on a chromebook, things in the downloads folder can often get deleted easily.
